### ISSUE TITLE
Android Invoking Method Channel calls results in ClassNotFoundException

### ISSUE THREAD

**Issue by nick-happsnow** [square/reader-sdk-flutter-plugin#100]
When attempting to invoke method channel calls to either check authorization with method channel call 'isAuthorized' or authorize Square with method channel call 'authorize', the following error occurs below. Since these errors occur, I am unable to authorize Square on Android devices. I do not get this same method channel problem on iOS. 

  **Error log details:**
 ` E/MethodChannel#square_reader_sdk(13497): Failed to handle method call
E/MethodChannel#square_reader_sdk(13497): java.lang.RuntimeException: java.lang.ClassNotFoundException: com.squareup.AppBootstrapFactory
E/MethodChannel#square_reader_sdk(13497): 	at com.squareup.sdk.reader.internal.AppBootstrapHolder.loadAppBootstrapFactory(AppBootstrapHolder.java:33)
E/MethodChannel#square_reader_sdk(13497): 	at com.squareup.sdk.reader.internal.AppBootstrapHolder.onCreate(AppBootstrapHolder.java:21)
E/MethodChannel#square_reader_sdk(13497): 	at com.squareup.sdk.reader.ReaderSdk.initialize(ReaderSdk.java:38)
E/MethodChannel#square_reader_sdk(13497): 	at com.squareup.sdk.reader.flutter.SquareReaderSdkFlutterPlugin.initializeReaderSdk(SquareReaderSdkFlutterPlugin.java:160)
E/MethodChannel#square_reader_sdk(13497): 	at com.squareup.sdk.reader.flutter.SquareReaderSdkFlutterPlugin.onMethodCall(SquareReaderSdkFlutterPlugin.java:79)
E/MethodChannel#square_reader_sdk(13497): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#square_reader_sdk(13497): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#square_reader_sdk(13497): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#square_reader_sdk(13497): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#square_reader_sdk(13497): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#square_reader_sdk(13497): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#square_reader_sdk(13497): 	at android.os.Looper.loop(Looper.java:246)
E/MethodChannel#square_reader_sdk(13497): 	at android.app.ActivityThread.main(ActivityThread.java:8625)
E/MethodChannel#square_reader_sdk(13497): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#square_reader_sdk(13497): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/MethodChannel#square_reader_sdk(13497): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
E/MethodChannel#square_reader_sdk(13497): Caused by: java.lang.ClassNotFoundException: com.squareup.AppBootstrapFactory
E/MethodChannel#square_reader_sdk(13497): 	at java.lang.Class.classForName(Native Method)
E/MethodChannel#square_reader_sdk(13497): 	at java.lang.BootClassLoader.findClass(ClassLoader.java:1358)
E/MethodChannel#square_reader_sdk(13497): 	at java.lang.BootClassLoader.loadClass(ClassLoader.java:1418)
E/MethodChannel#square_reader_sdk(13497): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/MethodChannel#square_reader_sdk(13497): 	at com.squareup.sdk.reader.internal.AppBootstrapHolder.loadAppBootstrapFactory(AppBootstrapHolder.java:30)
E/MethodChannel#square_reader_sdk(13497): 	... 15 more
E/MethodChannel#square_reader_sdk(13497): Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available`

**Environment:**
  - platform: Android
  - OS and version: Android 11 / 12 / 13
  - dev environment: MacOS
  - Reader SDK version: 4.0.0

**Flutter Doctor**
  [✓] Flutter (Channel stable, 3.0.5, on macOS 12.6 21G115 darwin-arm, locale en-US)
    • Flutter version 3.0.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (3 months ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

• No issues found!

**Comment by CharmisG** [comment]
@nick-happsnow 
Are you still facing the same ???

**Comment by CharmisG** [comment]
Closing this issue but if you still find this problem please reopen this issue. Thank you.

**Comment by hiporox** [comment]
@CharmisG I am running into this issue now, what changes were made about this?

**Comment by hiporox** [comment]
@CharmisG I found some info about this in the troubleshooting documentation, but it doesn't seem to solve the problem for me. Any suggestions?

**Comment by CharmisG** [comment]
@hiporox 
Can you share any screensort or any image of error so we can help you faster ?

**Comment by hiporox** [comment]
@CharmisG I am trying to run my app in debug mode using VSCode. I have tried the following:
1.  Changing the `build.gradle` to have `minifyEnabled false` and `shrinkResources false` as suggested in the troubleshooting

Doing so gives the following error:
```
Launching lib/main.dart on Pixel 6 in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:60742/DK4sGEu4WGE=/ws
I/heckout_manager( 9091): Compiler allocated 4413KB to compile void android.view.ViewRootImpl.performTraversals()
E/SurfaceSyncer( 9091): Failed to find sync for id=0
E/MethodChannel#square_reader_sdk( 9091): Failed to handle method call
E/MethodChannel#square_reader_sdk( 9091): java.lang.RuntimeException: java.lang.ClassNotFoundException: com.squareup.AppBootstrapFactory
E/MethodChannel#square_reader_sdk( 9091): 	at com.squareup.sdk.reader.internal.AppBootstrapHolder.loadAppBootstrapFactory(AppBootstrapHolder.java:33)
E/MethodChannel#square_reader_sdk( 9091): 	at com.squareup.sdk.reader.internal.AppBootstrapHolder.onCreate(AppBootstrapHolder.java:21)
E/MethodChannel#square_reader_sdk( 9091): 	at com.squareup.sdk.reader.ReaderSdk.initialize(ReaderSdk.java:38)
E/MethodChannel#square_reader_sdk( 9091): 	at com.squareup.sdk.reader.flutter.SquareReaderSdkFlutterPlugin.initializeReaderSdk(SquareReaderSdkFlutterPlugin.java:160)
E/MethodChannel#square_reader_sdk( 9091): 	at com.squareup.sdk.reader.flutter.SquareReaderSdkFlutterPlugin.onMethodCall(SquareReaderSdkFlutterPlugin.java:79)
E/MethodChannel#square_reader_sdk( 9091): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#square_reader_sdk( 9091): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#square_reader_sdk( 9091): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#square_reader_sdk( 9091): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#square_reader_sdk( 9091): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#square_reader_sdk( 9091): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#square_reader_sdk( 9091): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#square_reader_sdk( 9091): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#square_reader_sdk( 9091): 	at android.app.ActivityThread.main(ActivityThread.java:7884)
E/MethodChannel#square_reader_sdk( 9091): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#square_reader_sdk( 9091): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#square_reader_sdk( 9091): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/MethodChannel#square_reader_sdk( 9091): Caused by: java.lang.ClassNotFoundException: com.squareup.AppBootstrapFactory
E/MethodChannel#square_reader_sdk( 9091): 	at java.lang.Class.classForName(Native Method)
E/MethodChannel#square_reader_sdk( 9091): 	at java.lang.BootClassLoader.findClass(ClassLoader.java:1366)
E/MethodChannel#square_reader_sdk( 9091): 	at java.lang.BootClassLoader.loadClass(ClassLoader.java:1426)
E/MethodChannel#square_reader_sdk( 9091): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/MethodChannel#square_reader_sdk( 9091): 	at com.squareup.sdk.reader.internal.AppBootstrapHolder.loadAppBootstrapFactory(AppBootstrapHolder.java:30)
E/MethodChannel#square_reader_sdk( 9091): 	... 16 more
E/MethodChannel#square_reader_sdk( 9091): Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
D/ProfileInstaller( 9091): Installing profile for com.example.cyclei_checkout_manager
I/heckout_manager( 9091): Background concurrent copying GC freed 54470(5219KB) AllocSpace objects, 52(2448KB) LOS objects, 90% free, 2696KB/26MB, paused 364us,52us total 115.735ms
```

2. Not using VSCode's tooling, and instead building the app myself and then running it. I do this with the following:
`flutter build apk --no-shrink --debug` followed by `flutter run -d 1C231FDF600HMF --use-application-binary=build/app/outputs/flutter-apk/app-debug.apk`

This approach gives a similar error:
```
E/SurfaceSyncer(21141): Failed to find sync for id=0
E/MethodChannel#square_reader_sdk(21141): Failed to handle method call
E/MethodChannel#square_reader_sdk(21141): java.lang.RuntimeException: java.lang.ClassNotFoundException: com.squareup.AppBootstrapFactory
E/MethodChannel#square_reader_sdk(21141): 	at com.squareup.sdk.reader.internal.AppBootstrapHolder.loadAppBootstrapFactory(AppBootstrapHolder.java:33)
E/MethodChannel#square_reader_sdk(21141): 	at com.squareup.sdk.reader.internal.AppBootstrapHolder.onCreate(AppBootstrapHolder.java:21)
E/MethodChannel#square_reader_sdk(21141): 	at com.squareup.sdk.reader.ReaderSdk.initialize(ReaderSdk.java:38)
E/MethodChannel#square_reader_sdk(21141): 	at com.squareup.sdk.reader.flutter.SquareReaderSdkFlutterPlugin.initializeReaderSdk(SquareReaderSdkFlutterPlugin.java:160)
E/MethodChannel#square_reader_sdk(21141): 	at com.squareup.sdk.reader.flutter.SquareReaderSdkFlutterPlugin.onMethodCall(SquareReaderSdkFlutterPlugin.java:79)
E/MethodChannel#square_reader_sdk(21141): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#square_reader_sdk(21141): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#square_reader_sdk(21141): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#square_reader_sdk(21141): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#square_reader_sdk(21141): 	at android.os.Handler.handleCallback(Handler.java:942)
E/MethodChannel#square_reader_sdk(21141): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#square_reader_sdk(21141): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#square_reader_sdk(21141): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#square_reader_sdk(21141): 	at android.app.ActivityThread.main(ActivityThread.java:7884)
E/MethodChannel#square_reader_sdk(21141): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#square_reader_sdk(21141): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#square_reader_sdk(21141): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/MethodChannel#square_reader_sdk(21141): Caused by: java.lang.ClassNotFoundException: com.squareup.AppBootstrapFactory
E/MethodChannel#square_reader_sdk(21141): 	at java.lang.Class.classForName(Native Method)
E/MethodChannel#square_reader_sdk(21141): 	at java.lang.BootClassLoader.findClass(ClassLoader.java:1366)
E/MethodChannel#square_reader_sdk(21141): 	at java.lang.BootClassLoader.loadClass(ClassLoader.java:1426)
E/MethodChannel#square_reader_sdk(21141): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/MethodChannel#square_reader_sdk(21141): 	at com.squareup.sdk.reader.internal.AppBootstrapHolder.loadAppBootstrapFactory(AppBootstrapHolder.java:30)
E/MethodChannel#square_reader_sdk(21141): 	... 16 more
E/MethodChannel#square_reader_sdk(21141): Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
E/flutter (21141): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter (21141): Receiver: null
E/flutter (21141): Tried calling: []("debugCode")
E/flutter (21141): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:38:5)
E/flutter (21141): #1      ReaderSdk.isAuthorized (package:square_reader_sdk/reader_sdk.dart:35:63)
E/flutter (21141): <asynchronous suspension>
E/flutter (21141): #2      _SquareAuthHomeState.checkAuth (package:cyclei_checkout_manager/pages/square_auth/square_auth_home.dart:27:11)
```


This is the content of my `build.gradle`

```gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.cyclei_checkout_manager"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdkVersion localProperties.getProperty('flutter.minSdkVersion').toInteger()
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
            minifyEnabled false
            shrinkResources false
        }
        debug {
            minifyEnabled false
            shrinkResources false 
        }
    }

    dexOptions {
        // Ensures incremental builds remain fast
        preDexLibraries true
        // Required to build with Reader SDK
        jumboMode true
        // Required to build with Reader SDK
        keepRuntimeAnnotatedClasses false
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
```

**Comment by hiporox** [comment]
@CharmisG I have fixed the issue. Looks like the default flutter install uses an outdated gradle version. Updating gradle from 7.2.0 to 7.4.2 seems to have resolved the issue

**Comment by manandharsudhir** [comment]
Hello @CharmisG  I am faccing this issue currently I have tried searching everywhere but couldnt get any fixes
Herer is the screen shot of the error I am facing 
<img width="1335" alt="image" src="https://github.com/square/reader-sdk-flutter-plugin/assets/33796281/aa14819e-4d74-447c-be83-6643ab4e1f11">
Here is my build.gradle
`def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
// START: FlutterFire Configuration
apply plugin: 'com.google.gms.google-services'
// END: FlutterFire Configuration
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"
def keystoreProperties = new Properties()
   def keystorePropertiesFile = rootProject.file('key.properties')
   if (keystorePropertiesFile.exists()) {
       keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
   }
android {
    compileSdkVersion flutter.compileSdkVersion
    ndkVersion flutter.ndkVersion

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    defaultConfig {
        // TODO: Specify your own unique Appication ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.youthsummit.ys_field_app"
        // You can update the following values to match your application needs.
        // For more information, see: https://docs.flutter.dev/deployment/android#reviewing-the-gradle-build-configuration.
        minSdkVersion 24
        multiDexEnabled true
        targetSdkVersion flutter.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    dexOptions {
        // Ensures incremental builds remain fast
        preDexLibraries true
        // Required to build with Reader SDK
        jumboMode true
        // Required to build with Reader SDK
        keepRuntimeAnnotatedClasses false
    }
    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
         debug {
            minifyEnabled true

            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release
             applicationVariants.all{
                variant ->
                    variant.outputs.each{
                        output->
                            def name = "ys_field_app_v${variant.versionName}.apk"
                            output.outputFileName  = name
                    }
            }
        }
    }
    namespace 'com.youthsummit.ys_field_app'
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation("androidx.multidex:multidex:2.0.1")
}
`

**Comment by manandharsudhir** [comment]
@JakeWharton @emerose @maxbeatty will you help me with this

**Comment by manandharsudhir** [comment]
Solved this issue I was missing in my app level build.gradle
```
 minifyEnabled false
 shrinkResources false
```
