### ISSUE TITLE
How to cancel square checkout dialog programmatically 

### ISSUE THREAD

**Issue by Eimen2018** [square/reader-sdk-flutter-plugin#102]
### Describe your question

I was looking for a way to close the dialog after some time of inactivity but i could only find startCheckout there is no stop or cancel checkout which closes the dialog

**Comment by fka3** [comment]
In Reader SDK v1, that's correct, there isn't.  We do have a Reader SDK v2 in alpha, but haven't yet created the Flutter wrapper, nor GA'ed that version.
