### ISSUE TITLE
Android - Square Reader SDK interferes with other SDKs such as Stripe

### ISSUE THREAD

**Issue by nick-happsnow** [square/reader-sdk-flutter-plugin#103]
When integrating other SDKs with the Square Reader SDK such as Stripe Terminal on Android, the Square Reader SDK seems to break the functionality of other SDKs and I am unable to see Stripe Readers in my list. In my use case, it is the Stripe Terminal SDK. When I remove the Square Reader SDK from my project or remove it from pubspec.yaml, the Stripe Terminal SDK works again and I can connect to Stripe Readers. 

Is there a specific Android configuration that I am missing or need to add? I have an application that must work with the Square Reader SDK and the Stripe Terminal SDK.

I do get a duplicate class error for org.bouncycastle:
`Duplicate class org.bouncycastle.LICENSE found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1ApplicationSpecific found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1ApplicationSpecificParser found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1BitString found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1Boolean found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1Choice found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1Encodable found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)
     Duplicate class org.bouncycastle.asn1.ASN1EncodableVector found in modules jetified-bcprov-jdk15on-1.70 (org.bouncycastle:bcprov-jdk15on:1.70) and jetified-bcprov-jdk15to18-1.69 (org.bouncycastle:bcprov-jdk15to18:1.69)`

But I can resolve that with adding this to the app build.gradle:
`configurations.all {
        c -> c.resolutionStrategy.eachDependency {
            DependencyResolveDetails dependency ->
                println dependency.requested.group
                if (dependency.requested.group == 'org.bouncycastle') {
                    dependency.useTarget 'org.bouncycastle:bcprov-jdk15to18:1.69'
                }
        }
    }`

After adding that, I can compile my code but STILL cannot connect to a Stripe Reader.

Any help would be great. Thank you!

Environment:

platform: Android
OS and version: Android 11 / 12 / 13
dev environment: MacOS
Reader SDK version: 4.0.0
Flutter Doctor
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.6 21G115 darwin-arm, locale en-US)
• Flutter version 3.0.5
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision f1875d570e (3 months ago), 2022-07-13 11:24:16 -0700
• Engine revision e85ea0e79c
• Dart version 2.17.6
• DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
• Android SDK
• Platform android-33, build-tools 32.1.0-rc1
• Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
• Xcode at /Applications/Xcode.app/Contents/Developer
• CocoaPods version 1.11.3

[✓] Chrome - develop for the web
• Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

• No issues found!

**Comment by fka3** [comment]
Artem's answer is right; we don't see this as "our" bug (because our SDK works fine, as does Stripe's, and neither of us promise to work well with the other).  This is just a standard dependency conflict between different dependencies, but Artem suggested a strategy to make it work at the higher, sharing-of-both layer which has to own that conflict resolution.

**Comment by SudoPlz** [comment]
Confirming that `dependency.useTarget "org.bouncycastle:bcprov-jdk15to18:1.72"` works with both reader sdk and stripe sdk.
