### ISSUE TITLE
Device Not Supported

### ISSUE THREAD

**Issue by dirjud** [square/reader-sdk-flutter-plugin#107]
### Describe the issue
When connecting to a contactless reader on a Qukenk Android 11 tablet, I get a "Device Not Supported" popup after pairing completes.

The reader connects fine from the Square app. It is just in our custom app that this failure occurs. Attached are a sequence of screenshots showing the problem.

  Error log details:
  ```



  ```

**Environment (please complete the following information):**
  - Android
  - 11
  - Linux
  - 4.0.0

![Screenshot_20230130-043837](https://user-images.githubusercontent.com/147964/215355094-4f2acf90-552f-4691-aeaa-6c908c681e24.png)
![Screenshot_20230130-043848](https://user-images.githubusercontent.com/147964/215355097-4a16c6fe-35af-4f80-9de1-5ebe13ac128e.png)
![Screenshot_20230130-043851](https://user-images.githubusercontent.com/147964/215355098-4eba0826-be47-453a-a183-4909b7145dc8.png)
![Screenshot_20230130-043910](https://user-images.githubusercontent.com/147964/215355099-e9a36528-0a27-48b9-ac66-49e125131dd4.png)
![Screenshot_20230130-044052](https://user-images.githubusercontent.com/147964/215355100-50041e74-a574-4801-bcdb-551f0f3c6fab.png)
![Screenshot_20230130-044056](https://user-images.githubusercontent.com/147964/215355101-699cc48f-3aec-40e5-bdb4-f5c507668e7b.png)

**Comment by Armaxis** [comment]
Hello! We checked the logs on our end and it looks like this device doesn't pass the hardware security check. 
You can try formatting the device, resetting it back to the factory settings, to fix the issue. Alternatively, you can try using a different Android phone or tablet.
Hope this helps!

**Comment by fka3** [comment]
I doubt the network connectivity stuff is related; not sure why the robot thought it was.

The "device not compatible" is, as Artem said, the hardware security layer... and the rules for that are slightly different for RSDK vs POS, but in general POS is stricter (because it's our app, so we can be more forceful about what it needs).

**Comment by hiporox** [comment]
@Armaxis @fka3 I am having the same issue as OP. I tried a factory reset and it still doesn't work. What are settings on the device that could be causing this?

**Comment by Armaxis** [comment]
@hiporox can you please share some information?
- What device are you using? 
- Merchant ID
- Reader SDK Application ID
- Approximate time of failure to pair
You can send the info securely here: https://squareup.sendsafely.com/u/artem

**Comment by hiporox** [comment]
@Armaxis I sent you that info on the send safely site

**Comment by Armaxis** [comment]
@hiporox I see that this device doesn't pass the [Safetynet](https://developer.android.com/training/safetynet) check. Does it have latest Google Play Store components installed?
Also, is it a rooted device?

You can [use this app](https://play.google.com/store/apps/details?id=org.freeandroidtools.safetynettest&hl=en_US&gl=US) to test your phone for Safetynet

**Comment by hiporox** [comment]
It's failing on the CTS Profile Match. The device isn't rooted, opened it straight from the box. It doesn't appear to be Play Certified. I'm gonna talk with the manufacturer about what's going on

**Comment by Armaxis** [comment]
Oh, interesting, so it doesn't run the stock Android, right? 
I'd definitely be cautious of using these devices in production, this doesn't sound too secure

**Comment by hiporox** [comment]
It does run stock Android, but speaking to the manufacturer, they didn't submit the version they shipped it with to Google for certification. I won't be using an unsecured OS in production
