### ISSUE TITLE
Apply Taxes

### ISSUE THREAD

**Issue by LEHOANGLONG0807** [square/reader-sdk-flutter-plugin#109]
Hi, can I apply Taxes using this package?

**Comment by fka3** [comment]
Not really, no.  Certainly you can (and should!) ask for a payment amount that includes taxes, but the SDK itself doesn't know what you're selling or where to know, for example, that it's the liquor tax rate from Massachusetts that should apply.  And it especially doesn't know that half the payment has one kind of item with one tax rate, but the other half are for another kind of item with a different tax rate.
