### ISSUE TITLE
Need to minimize footprint

### ISSUE THREAD

**Issue by kevin-haynie** [square/reader-sdk-flutter-plugin#38]
OK, I got your example compiled and was able to make a $1.00 cash charge - which is very cool.  BUT, your simple example app is 130MB big in debug mode for iOS and 103MB big in release mode.  

Looks like you have a 56MB! 'SquareReaderSDK' file in your framework which gets linked in!  OUCH.

Although I really need this functionality for my Flutter POS app, I can't afford to bloat my app this much.  Is there any way to reduce the footprint?  The other problem with having such a large library is that it's increased my build times by about 2x - which is really bad.

I've just looked at your 'Point-of-Sale API' and I believe this would work as well but I don't see any Flutter versions of this SDK.  Are there any plans to implement this?  I believe this would reduce my footprint by quite a bit but correct me if I'm wrong...

Thanks
Kevin

**Comment by StephenJosey** [comment]
Unfortunately you're right on both of your inquiries. ReaderSDK is a bit bloated, and there's no real way to trim it down for your release. There's definitely been discussions around this before, but I do not have an ETA on when or if it'll be resolved.

To address your second question about the POS API: there is not a Flutter plugin for it, and again I'm not able to provide an ETA on when or if one will be created.

**Comment by sseaman** [comment]
Closing as there is no plan to reduce the size of the ReaderSDK at this time.

Also, as stated previously, no POS flutter planned at this time.  However, we'll add it to the backlog to see if we can get to it someday.
