### ISSUE TITLE
Production builds break with Flutter 1.12

### ISSUE THREAD

**Issue by ryan-berger** [square/reader-sdk-flutter-plugin#42]
### Describe the issue

Flutter 1.12 just added the breaking change of adding `android.enableR8=true` which obfuscates libraries. This causes the Square Reader SDK to stop functioning.

Each time you open the app, it immediately crashes and logcat outputs this error:

`Unable to create application com.example.test.MainApplication: java.lang.RuntimeException: java.lang.ClassNotFoundException: Didn't find class "com.squareup.AppBootstrapFactory" on path: DexPathList`

### To Reproduce

Upgrade to flutter 1.12.13+hotfix6 (or any of the 1.12.13 releases), run `flutter build apk --release` and you will notice that automatically `android.enableR8=true` is added to your `gradle.properties` file.

**Comment by okenshields** [comment]
Hi Ryan,
Currently Reader SDK does not work with Proguard (or R8). It's mentioned in the **Prerequisites and assumptions** section here https://developer.squareup.com/docs/reader-sdk/build-on-android: `You are not using Proguard for code optimization. Compressing the Reader SDK binary removes critical bytecode elements and results in runtime errors.`
Can you try disable code shrinking/obfuscation? Thanks!

**Comment by ryan-berger** [comment]
@okenshields Disabling r8 still breaks it as flutter must have added another breaking change to use proguard if r8 gets disabled.

If you use the following `buildTypes` config in your `app/build.gradle`
```
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            shrinkResources false
        }
    }```

it will work. Because it doesn't work out of the box without any sort of gradle configuration changes, would we be able to add this to the setup docs? If you would like I can submit a PR

**Comment by okenshields** [comment]
@ryan-berger , feel free to send a PR for this. Thanks!

**Comment by mohsin-sq** [comment]
I have added the documentation for this issue. closing!
