### ISSUE TITLE
Change APP ID at run time

### ISSUE THREAD

**Issue by CurtHubb** [square/reader-sdk-flutter-plugin#43]
We're creating a flutter app that we'd like to integrate square for customers to use, unfortunately it appears you must hard code the App ID and Password in the gradle.properties currently. Is it possible to adjust the plugin so the App ID and Password can be updated later?

**Comment by StephenJosey** [comment]
What exactly are you trying to do (what do you mean by integrate for customers to use)? Ie, even though you have the app id and password, you still need to authorize the application which requires a [mobile authorization code](https://developer.squareup.com/docs/mobile-authz/what-it-does). This code can be generated on a per-Square-merchant basis via [OAuth](https://developer.squareup.com/docs/oauth-api/what-it-does). 

So, if you're wanting many Square merchants to use your application, you would just need to get them to OAuth, which basically asks them to allow your application to have access to their account, which will generate a unique access token. Using this access token, you can call the mobile auth endpoint to generate a unique code to authorize the particular device they're using. Please let me know if I'm misunderstanding, though.

**Comment by CurtHubb** [comment]
Steven, 

Thanks for the response. Sorry I didn't explain properly but I think you've got it, we want many Square merchants to be able to use our application. I guess my confusion is stemming from the directions on getting started that require you to place the App Id and Password in the gradle.properties on Android and pass it in when downloading the SDK for iOS.

**Comment by StephenJosey** [comment]
Hi @CurtHubb correct. That basically ties the application to your Square application. However, the authentication that can be called dynamically (https://github.com/square/reader-sdk-flutter-plugin/blob/master/doc/reference.md#authorize) will be what Square account the transactions will be tied to. So, via OAuth, when a merchant downloads your app, they would be granted an access token, and your application would (behind the scenes) create a mobile auth token, and call the above `authorize` function with the auth token, all before they could take a payment. Once it's authorized, it will be linked to their Square account, and payments will be sent to their Square account.
