### ISSUE TITLE
Module 'SquareReaderSDK' not found

### ISSUE THREAD

**Issue by dirjud** [square/reader-sdk-flutter-plugin#56]
I am trying to compile the example, and I get a Parse Issue: Module 'SquareReaderSDK' not found

Error Log:
    /Users/lane/Documents/reader-sdk-flutter-plugin/ios/Classes/Converters/SQRDT
    enderCashDetails+FlutterReaderSDKAdditions.m:17:
    /Users/lane/Documents/reader-sdk-flutter-plugin/ios/Classes/Converters/SQRDT
    enderCashDetails+FlutterReaderSDKAdditions.h:17:9: fatal error: module
    'SquareReaderSDK' not found
    @import SquareReaderSDK;
     ~~~~~~~^~~~~~~~~~~~~~~
    1 error generated.


### To Reproduce
Steps to reproduce the issue:
1. git clone git@github.com:square/reader-sdk-flutter-plugin.git
2. cd reader-sdk-flutter-plugin/example
3. rm ios/PodFile
3. flutter pub get
4. edit ios/PodFile to set platform to 11.1
4. flutter build iOS


**Environment (please complete the following information):**
platform: iOS
macOS: 11.2.2
Flutter 2.1.0-11.0.pre.145 • channel master •
https://github.com/flutter/flutter.git
Framework • revision a0ba646408 (22 hours ago) • 2021-03-05 22:09:03 -0500
Engine • revision f751d04fa0
Tools • Dart 2.13.0 (build 2.13.0-107.0.dev)
Reader SDK:

**Comment by StephenJosey** [comment]
For the sample (https://github.com/square/reader-sdk-flutter-plugin/blob/master/example/README.md), did you install the SDK per the instructions in the `ios` directory?

```
ruby <(curl https://connect.squareup.com/readersdk-installer) install \
--app-id YOUR_SQUARE_READER_APP_ID                                    \
--repo-password YOUR_SQUARE_READER_REPOSITORY_PASSWORD
```

**Comment by dirjud** [comment]
Yes, I have run the following commands:
```
cd ios
ruby <(curl https://connect.squareup.com/readersdk-installer) install --app-id XXXX --repo-password XXXX

```
I got the following result:
> Installed version 1.4.7: /Users/lane/Documents/reader-sdk-flutter-plugin/example/ios/SquareReaderSDK.xcframework

I then run
```
cd ..
flutter run
```
and I get the following:

> Launching lib/main.dart on iPad Pro (12.9-inch) (4th generation) in debug
mode...
> Running pod install...                                           2,524ms
> Running Xcode build...                                                  
> Xcode build done.                                           17.2s
> Failed to build iOS app
> Error output from Xcode build:
> ↳
>     ** BUILD FAILED **
> 
> 
> Xcode's output:
> ↳
>     In file included from
>     /Users/lane/Documents/reader-sdk-flutter-plugin/ios/Classes/Converters/SQRDT
>     enderCashDetails+FlutterReaderSDKAdditions.m:17:
>     /Users/lane/Documents/reader-sdk-flutter-plugin/ios/Classes/Converters/SQRDT
>     enderCashDetails+FlutterReaderSDKAdditions.h:17:9: fatal error: module
>     'SquareReaderSDK' not found
>     @import SquareReaderSDK;
>      ~~~~~~~^~~~~~~~~~~~~~~
>     1 error generated.
>     In file included from
>     /Users/lane/Documents/reader-sdk-flutter-plugin/ios/Classes/Converters/SQRDT
>     enderCardDetails+FlutterReaderSDKAdditions.m:17:
>     /Users/lane/Documents/reader-sdk-flutter-plugin/ios/Classes/Converters/SQRDT
> 
> 
>     enderCardDetails+FlutterReaderSDKAdditions.h:17:9: fatal error: module
>     'SquareReaderSDK' not found
>     @import SquareReaderSDK;
>      ~~~~~~~^~~~~~~~~~~~~~~
>     1 error generated.
>     note: Using new build system
>     note: Building targets in parallel
>     note: Planning build
>     note: Constructing build description
> 
> Could not build the application for the simulator.
> Error launching application on iPad Pro (12.9-inch) (4th generation).
>

**Comment by dirjud** [comment]
I wonder if this is a problem with the Podfile. When I clone a fresh copy and run
```flutter run```
I get the following error:

> Lanes-MacBook-Air:ios lane$ flutter run
> Changing current working directory to:
> /Users/lane/Documents/reader-sdk-flutter-plugin/example
> Launching lib/main.dart on iPad Pro (12.9-inch) (4th generation) in debug
> mode...
> Running pod install...                                              5.7s
> Warning: Podfile is out of date
>   This can cause issues if your application depends on plugins that do not
>   support iOS or macOS.
>   See
>   https://flutter.dev/docs/development/packages-and-plugins/developing-packages#
>   plugin-platforms for details.
>   If you have local Podfile edits you would like to keep, see
>   https://github.com/flutter/flutter/issues/45197 for instructions.
> To regenerate the Podfile, run:
> 
>   rm ios/Podfile
> 
> 
> Error launching application on iPad Pro (12.9-inch) (4th generation).
> 

So I run 'rm Podfile' and 'flutter run' again and get this error:

> Lanes-MacBook-Air:example lane$ rm ios/Podfile
> Lanes-MacBook-Air:example lane$ flutter run
> Launching lib/main.dart on iPad Pro (12.9-inch) (4th generation) in debug
> mode...
> Running pod install...                                              3.5s
> Running Xcode build...                                                  
> Xcode build done.                                           10.6s
> Failed to build iOS app
> Error output from Xcode build:
> ↳
>     ** BUILD FAILED **
> 
> 
> Xcode's output:
> ↳
>     In file included from
>     /Users/lane/Documents/readerTest/ios/Classes/Converters/SQRDTenderCashDetail
>     s+FlutterReaderSDKAdditions.m:17:
>     /Users/lane/Documents/readerTest/ios/Classes/Converters/SQRDTenderCashDetail
>     s+FlutterReaderSDKAdditions.h:17:9: fatal error: module 'SquareReaderSDK'
>     not found
>     @import SquareReaderSDK;
>      ~~~~~~~^~~~~~~~~~~~~~~
>     1 error generated.
>     In file included from
>     /Users/lane/Documents/readerTest/ios/Classes/Converters/SQRDTenderCardDetail
>     s+FlutterReaderSDKAdditions.m:17:
>     /Users/lane/Documents/readerTest/ios/Classes/Converters/SQRDTenderCardDetail
>     s+FlutterReaderSDKAdditions.h:17:9: fatal error: module 'SquareReaderSDK'
>     not found
>     @import SquareReaderSDK;
>      ~~~~~~~^~~~~~~~~~~~~~~
>     1 error generated.
>     note: Using new build system
>     note: Building targets in parallel
>     note: Planning build
>     note: Constructing build description
> 
> Could not build the application for the simulator.
> Error launching application on iPad Pro (12.9-inch) (4th generation).
> Lanes-MacBook-Air:example lane$ 
> 

So then I edit the Podfile to say:

`platform :ios, '11.1'`

I run 'flutter clean' and 'flutter run' again and get the same exact failure.  If I run `git diff ios/Podfile` the files are *very* different.

**Comment by StephenJosey** [comment]
Hm, could you try doing these steps as well: https://developer.squareup.com/docs/reader-sdk/build-on-ios#step-3-configure-your-ios-project-for-reader-sdk (mainly the build phase step)? Wondering if this was intentionally left out of these flutter docs.

**Comment by dirjud** [comment]
Here is what the build phases scripts said prior to my edit:
```
if [ "$DEVELOPMENT_TEAM" != "" ]
then
FRAMEWORKS="${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}"
"${FRAMEWORKS}/SquareReaderSDK.framework/setup"
else
echo "Skip sign frameworks"
fi

```

**Comment by StephenJosey** [comment]
Apologies for the delay here, I am escalating to our SDK team for further investigation. Please let me know if you were able to figure this out though.

**Comment by dirjud** [comment]
It's still an issue for me.

**Comment by djmuhlestein** [comment]
Issue for me as well.  Same setup w/ latest OSX/Xcode.  Doesn't look to me like the script is being run although I'm not sure if that's what's causing the build error.   

Error says "Module SquareReaderSDK not found" at SQRDTenderCardDetails+FlutterReaderSDKAdditions.h line 17

**Comment by dirjud** [comment]
building against the branch for pull request 59 works.

**Comment by MuneebQureshi1** [comment]
The framework will install in the current ios directory.

Step 1:-

Move to project_root_directory/ios
Step 2:-

Run this command

ruby <(curl https://connect.squareup.com/readersdk-installer) install
--app-id YOUR_SQUARE_READER_APP_ID
--repo-password YOUR_SQUARE_READER_REPOSITORY_PASSWORD

Make sure to replace YOUR_SQUARE_READER_APP_ID with your Square Reader application ID and YOUR_SQUARE_READER_REPOSITORY_PASSWORD with your Square Reader repository password.
