### ISSUE TITLE
Issue using both square payments sdk and reader sdk together

### ISSUE THREAD

**Issue by nneuberger1** [square/reader-sdk-flutter-plugin#69]
### Describe your question

I'm attempting to integrate the square_reader_sdk into my flutter application but having issues with pulling it in. I'm using the 3.0.0 version of the sdk because I'm also using the square_in_app_payments in the same project.

Here's my pubspec.yaml dependencies:

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.0-nullsafety.0
  uuid: 3.0.4
  intl: ^0.17.0
  socket_io_client: ^2.0.0-beta.2
  logger: ^1.0.0
  square_in_app_payments: ^1.7.1
  square_reader_sdk: ^3.0.0
  cupertino_icons: ^1.0.2

I'm trying to run an iOS Simulator via Android Studio. This is to just get it into a compiled state. IIRC, the reader-sdk-flutter-plugin sample doesn't run in simulator and connects, so this is my first step before moving to a physical device for sdk reader connections.

In Xcode Runner project, I see the following error on GeneratedPluginRegistrant.m

Module 'square_reader_sdk' not found

on this line.
@import square_reader_sdk;

When running in Android Studio, here's the console output error.

Xcode's output:
↳
    /Users/nickneuberger/ws/mwog/liberty/liberty_flutter/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'square_reader_sdk' not found
    @import square_reader_sdk;
     ~~~~~~~^~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace


I have the reader-sdk-flutter-plugin sample project running and launching via Android Studio into a simulator just fine, but it's pubspec.yaml file doesn't even specify the square_reader_sdk in it's dependencies.

Any help would greatly be appreciated.

**Comment by nneuberger1** [comment]
Stumbled on this bad boy and still haven't found any solutions to this dreaded problem.

[ios][release] GeneratedPluginRegistrant.m Module not found #43986
https://github.com/flutter/flutter/issues/43986#issuecomment-605987016

**Comment by divyeshgohil85** [comment]
Any solution for this? We need these both together for following requirement. 
-If customer has Square Gift Card number, we need In-App sdk to take partial/full payment from gift-card by Key-In
-Remaining payment using card swipe through reader

**Comment by nneuberger1** [comment]
I haven't resolved the issue on my side yet. I may jump back to payments in the next several weeks and attempt to resolve it. If I resolve the issue, I'll resolve it. maybe some of square devs can shed some light on it.

**Comment by fka3** [comment]
Realizing we're a year late in replying, but we really don't intend that IAP and RSDK be used together... IAP is buyer-facing and doesn't even have a login, and your server (probably, since the app isn't even logged in) has to create payments from its nonces, whereas RSDK takes payments entirely, including by manual entry, but is logged in as a merchant.  How do you have the two use cases intersecting?
