### ISSUE TITLE
Will not build on iOS

### ISSUE THREAD

**Issue by emmett-deen** [square/reader-sdk-flutter-plugin#76]
### Describe the issue
I have battled with build errors on iOS for the last couple hours. I decided to use this pr: https://github.com/square/reader-sdk-flutter-plugin/pull/74 as it seemed to be the most promising since it was at least up to date.

Here were some of the issues I was faced with:
1. Linking error - The recommendation of the Legacy Build System no longer works. When switching to legacy I received errors from XCode about the legacy system not supporting xcframeworks. When trying to import just the arm64 framework I was met with a similar error saying that the specific framework was not supported by the legacy build system.
2. Bitcode error - Although bitcode was enabled for my flutter target it kept requesting me to generate bitcode for the framework or disable bitcode for the current target. This was solved by adding a line to the podfile to disable bitcode for all pods. There was no mention of this issue in the documentation.
3. Flutter: include of non-modular header inside framework module - This was also solved by adding a line to the podfile allowing non-modular frameworks & also setting a flag in xcode for the flutter target allowing this
4. The last error I wasn't able to solve was: module not found for just the "square_reader_sdk" in the GeneratedPluginRegistrant.m file

### To Reproduce
Follow getting started steps on a newly initialized flutter project

### Expected behavior
1. Enhanced troubleshooting documentation
2. Updated documentation around flutter 2.5+
3. Working version of https://github.com/square/reader-sdk-flutter-plugin/pull/74 to be merged into develop

**Environment (please complete the following information):**
Xcode version 13.0
iOS

```[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6 20G165 darwin-x64, locale en-US)
    • Flutter version 2.5.3 at /Users/emmettdeen/Developement/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (12 days ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/emmettdeen/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 95.0.4638.54

• No issues found!```

**Comment by ben-wood** [comment]
> ### Describe the issue
> I have battled with build errors on iOS for the last couple hours. I decided to use this pr: #74 as it seemed to be the most promising since it was at least up to date.
> 
> Here were some of the issues I was faced with:
> 
> 1. Linking error - The recommendation of the Legacy Build System no longer works. When switching to legacy I received errors from XCode about the legacy system not supporting xcframeworks. When trying to import just the arm64 framework I was met with a similar error saying that the specific framework was not supported by the legacy build system.
> 2. Bitcode error - Although bitcode was enabled for my flutter target it kept requesting me to generate bitcode for the framework or disable bitcode for the current target. This was solved by adding a line to the podfile to disable bitcode for all pods. There was no mention of this issue in the documentation.
> 3. Flutter: include of non-modular header inside framework module - This was also solved by adding a line to the podfile allowing non-modular frameworks & also setting a flag in xcode for the flutter target allowing this
> 4. The last error I wasn't able to solve was: module not found for just the "square_reader_sdk" in the GeneratedPluginRegistrant.m file
> 
> ### To Reproduce
> Follow getting started steps on a newly initialized flutter project
> 
> ### Expected behavior
> 1. Enhanced troubleshooting documentation
> 2. Updated documentation around flutter 2.5+
> 3. Working version of [Bump reader SDK version to 1.5.1 in plugin. #74](https://github.com/square/reader-sdk-flutter-plugin/pull/74) to be merged into develop
> 
> **Environment (please complete the following information):** Xcode version 13.0 iOS
> 
> ```
>     • Flutter version 2.5.3 at /Users/emmettdeen/Developement/flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision 18116933e7 (12 days ago), 2021-10-15 10:46:35 -0700
>     • Engine revision d3ea636dc5
>     • Dart version 2.14.4
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at /Users/emmettdeen/Library/Android/sdk
>     • Platform android-30, build-tools 30.0.2
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 13.0, Build version 13A233
>     • CocoaPods version 1.11.2
> 
> [✓] Chrome - develop for the web
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 2020.3)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>       🔨 https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
> 
> [✓] VS Code (version 1.61.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.27.0
> 
> [✓] Connected device (2 available)
>     • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
>     • Chrome (web)                       • chrome        • web-javascript • Google Chrome 95.0.4638.54
> 
> • No issues found!```
> ```

Had the same issues. I re-generated the flutter application using android studio and selected Java and Objective-C as the base languages instead of Java and Swift. Once I did that I was able to follow the instructions and implement the plugin in my app. 

So this seems related to the lack of swift support.

Thanks
Ben

**Comment by CharmisG** [comment]
@ben-wood , @emmett-deen 
We had done swift conversion for example folder and now it's working please check and let me know if you are still facing same issue.
