### ISSUE TITLE
Compiled application with target SDK 31 fails to install on android device

### ISSUE THREAD

**Issue by TatsuUkraine** [square/reader-sdk-flutter-plugin#78]
### Describe the issue
During app build with target SDK 31 in the gradle config, app fails to install with message

```com.squareup.queue.QueueService$BootReceiver: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]```

### To Reproduce
Create new project with Flutter 2.8. By default gradle in the flutter 2.8 uses compile SDK and target SDK equals to 31. Or just update app gradle config in the existing app with target sdk 31

### Expected behavior
The app should be successfully installed on a device.

**Environment (please complete the following information):**

  - platform: Android
  - OS and version: Android 12
  - dev environment: MacOS
  - Reader SDK version: 1.5.3 (can assume it's a most recent version)

[✓] Flutter (Channel stable, 2.8.0, on macOS 11.4 20F71 darwin-x64, locale ru-UA)
    • Flutter version 2.8.0 at .....
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (12 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at .......
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.1

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (2 available)
    • Pixel 5 (mobile) • 0B021FDD4000CA • android-arm64  • Android 12 (API 31)

• No issues found!

**Comment by TatsuUkraine** [comment]
@CharmisG I tried to use Android SDK 1.5.6 and it crashes on the Android emulator

**Comment by CharmisG** [comment]
@TatsuUkraine 
Are you still facing same issue ??

**Comment by TatsuUkraine** [comment]
Nope, it was fixed with v4 release
