### ISSUE TITLE
delayCapture doesn't work with Android Reader SDK 1.5.5

### ISSUE THREAD

**Issue by TatsuUkraine** [square/reader-sdk-flutter-plugin#79]
### Describe the issue
delayCapture=true in CheckoutParametersBuilder doesn't make Transaction as delayed

### To Reproduce

  1. Initialize the SDK
  1. Let Gradle download the most recent Android Reader SDK version (1.5.5)
  1. try to create delayed transaction

### Expected behavior
The transaction should be in the "Awaiting capture" state

**Environment (please complete the following information):**

  - platform: Android
  - OS and version: Android 12
  - dev environment: MacOS
  - Reader SDK version: 1.5.5

### Additional context
I didn't find any mentions of 1.5.5 release in the release notes. Probably it was mistakenly published. SDK for version still downloads 1.5.4.

If override Reader SDK version in gradle like this all works fine.
```
rootProject.ext {
    readerSdkVersion = '1.5.4'
}
```

**Comment by CharmisG** [comment]
Sorry For Delay @TatsuUkraine 
We had upgraded plugin so you can pull latest code and let me know if you are still facing this issue.
