### ISSUE TITLE
Restore internet to accept payment

### ISSUE THREAD

**Issue by Memet18** [square/reader-sdk-flutter-plugin#81]
### Describe the issue

 We have connected the SDK to our application and sometimes we have a problem where the message "Restore internet to accept payment" appears when the internet connection is bad. And even after the restoration of the Internet, the message no longer disappears and this message appears with all payments. Watch the video for more details.
        

### To Reproduce
   Video showing how
https://photos.app.goo.gl/z4dkEfGtXiThmQuK6

### Expected behavior
  After the Internet connection is restored, the message "Restore internet to accept payment" should disappear

**Environment (please complete the following information):**
  - platform: [Android]
  - OS and version: [Android 11]
  - dev environment: [MacOS ]
  - Reader SDK version: [1.5.1]

### Screenshots
<img width="575" alt="Снимок экрана 2022-03-19 в 00 31 49" src="https://user-images.githubusercontent.com/54338732/159096896-e64fb8c8-83de-4969-ae40-668096b7a085.png">

**Comment by CharmisG** [comment]
@Memet18 

Sorry for the delay !!
We Released new version please check in latest code and feel free to reopen issue again if you are facing the same.

Thank you !!!
