### ISSUE TITLE
Failing on APK build :square_reader_sdk:verifyReleaseResources

### ISSUE THREAD

**Issue by emmett-deen** [square/reader-sdk-flutter-plugin#85]
### Describe the issue

  When running `flutter build apk` the build fails with the below error. The build does not fail when building for iOS or when building an appbundle using `flutter build appbundle`

  Error log details:
  ```
* What went wrong:
Execution failed for task ':square_reader_sdk:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:/Users/emmettdeen/.gradle/caches/transforms-3/3798f500c70376b24c117fdb9741f1e1/transformed/core-1.7.0/res/values/values.xml:105:5-114:25: AAPT: error: resource android:attr/lStar not found.
  ```

### To Reproduce
  Run `flutter build apk`

**Comment by wade-beavers** [comment]
I am having the same issue

**Comment by alsummers** [comment]
I am having the same issue before and after upgrading to flutter version 3.0.0
