### ISSUE TITLE
Compiled application with target SDK 31 fails to install on android device

### ISSUE THREAD

**Issue by TatsuUkraine** [square/reader-sdk-flutter-plugin#87]
Compiled application with target SDK 31 fails to install on android device

**Comment by CharmisG** [comment]
@TatsuUkraine 
We have changed compile version with 32 which is latest in android.
Please try latest code and let know if you are still facing same issue.

**Comment by CharmisG** [comment]
@TatsuUkraine
We couldn’t replicate this issue in example app so can you please give us more information about this issue ?

**Comment by TatsuUkraine** [comment]
@CharmisG so it seems it's related to the fact that you need explicitly request 2 Bluetooth permission before initialize is invoked. App with the permission exception.

I spent some time to figure a workaround since there is no mention of it at all

**Comment by CharmisG** [comment]
@TatsuUkraine 
Can you please share screenshot of issue ?

**Comment by TatsuUkraine** [comment]
@CharmisG I think I put wrong description there, app installs, it crashes on launch because of missing permissions. This issue you was trying to solve by adding permissions to manifest file

**Comment by TatsuUkraine** [comment]
@CharmisG but this PR https://github.com/square/reader-sdk-flutter-plugin/pull/90 doesn't solve anything, because these permissions belongs to a dangerous permissions
