### ISSUE TITLE
Reader SDK support for M1 Mac computers - iOS Xcode

### ISSUE THREAD

**Issue by nick-happsnow** [square/reader-sdk-flutter-plugin#92]
I am currently developing a Flutter app and utilizing the square_reader_sdk package. Once I integrate the square_reader_sdk and follow all of the steps to set it up using this link for iOS: [reader-sdk-flutter-plugin/get-started.md at master · square/reader-sdk-flutter-plugin · GitHub](https://github.com/square/reader-sdk-flutter-plugin/blob/master/doc/get-started.md), my project in Xcode generates Module ‘X’ not found errors. No matter how hard I try to resolve these errors, they still remain. If I remove the square_reader_sdk package, the module errors go away. The square_reader_sdk version that I am using is on version 3.0.0.

I am developing on a Mac M1 Pro and using Flutter version 3.0.5. I am also running Xcode 13.4.1. I am more than happy to share more information if needed. I believe that I read somewhere that Square still does not support M1 computers. If this is the case or the cause of my issue, when will M1 computers be supported?

Any help to get the iOS build compiling and succeeding would be much appreciated.

Thank you!

  - platform: iOS
  - OS and version: iOS 15.6
  - dev environment: macOS Monterey 12.2.1
  - Reader SDK version: 3.0.0

### Flutter Doctor:

  [✓] Flutter (Channel stable, 3.0.5, on macOS 12.2.1 21D62 darwin-arm, locale en-US)
    • Flutter version 3.0.5
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1875d570e (6 weeks ago), 2022-07-13 11:24:16 -0700
    • Engine revision e85ea0e79c
    • Dart version 2.17.6
    • DevTools version 2.12.2

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

• No issues found!
Process finished with exit code 0

### Screenshots
![image](https://user-images.githubusercontent.com/102989457/185999111-9c6145b2-8c43-427c-8576-195459b0cc13.png)

**Comment by TatsuUkraine** [comment]
had the same issue, it happening because of the wrong iOS config override in the plugin itself
